### PR TITLE
dnbinom accuracy

### LINKED ISSUE #401: dnbinom inaccuracy in poisson limit
Reported by @bbolker on https://groups.google.com/g/tmb-users/c/z9KhTjO3FfE

Demonstration code based on `RTMB`:

```r
x <- 1; mu <- 1
var_minus_mu <- 10^seq(-20, 0, length = 101)
## var = mu*(1+mu/theta) -> var_minus_mu = mu^2/theta -> theta =
mu^2/var_minus_mu
thetavec <- mu^2/var_minus_mu
varvec <- mu + var_minus_mu ## will underflow ...

fixtmb <- function(x) Im(unclass(x))
v1 <- dnbinom(x = x, mu = mu, size = thetavec, log = TRUE)
v2 <- RTMB::dnbinom2(x = x, mu = mu, var = varvec, log = TRUE) |> fixtmb()
v3 <- RTMB::dnbinom_robust(x = x, log_mu = log(mu),
log_var_minus_mu = log(var_minus_mu),
log = TRUE) |> fixtmb()

par(las = 1, bty = "l")
matplot(thetavec, cbind(v1, v2, v3), type = "l", log = "x",
ylim = c(-2, 0), lwd = 2, col = c(1,2,4),
ylab = "log LL")
abline(h = dpois(1, 1, log = TRUE), lty = 2) 
```

### PR DESCRIPTION
**Pull request by kaskr**
Fix #401 

Using `lbeta` as proposed by @bbolker to fix the accuracy issue.
The change introduced a performance regression which has also been fixed.

### CODE REVIEW

**Comment by bbolker** [comment]
It would be nice to fix `dnbinom` and `dnbinom2` similarly while we're at it (although there is an argument that people who really want stability should go straight to `dbinom_robust` ...) 

- for `dnbinom`, it seems that just substituting `-lbeta(n,x) -log(x)` for `lgamma(x + n) - lgamma(n) - lgamma(x + 1.)` should be all that's necessary (do we need a branch as in `dnbinom_robust` for variable vs constant `x` for performance?)

R implements `dnbinom_mu` separately from `dnbinom()` because the parameter conversion from `(mu, size)` to `(prob, size)`, i.e. `prob :=  size / (size + mu)`, is unstable when `size >> mu`

The code from base R, tweaked by Martin Maechler over the years, is [here](https://github.com/r-devel/r-svn/blob/main/src/nmath/dnbinom.c#L94-L110).  To adapt:

* decide whether we need all the branches
* can branching be done safely with `CppAD::CondExpLt` in this context?
* does `TMB` have an analogue of `lgamma1p`? (It has `lfactorial`, but that doesn't look like it's robust - it's just sugar for computing `lgamma(a+1)`, doesn't try to be numerically stable)
* do we need an additional branch for performance as in `dnbinom_robust` ?
* convert code from `size, mu` to `var, mu` parameterization ; this requires a little bit of extra work, because deriving `n` from `var` (`mu/(var/mu - 1)`) also requires extra care/branching when `var/mu` is close to 1 ...

**Comment by bbolker** [comment]
More exploration [here](https://github.com/mikeroswell/epiExplore/blob/main/nbinom_stability.R).

This compares base R `dnbinom` with RTMB's `dnbinom2` and `dnbinom_robust` (the current version that uses `lbeta`) for `x=1, mu=1`, wide range of theta/dispersion parameter:

tmp-0

Looks like `dnbinom_robust` is fine, while `dnbinom2` is still bad.

But if we do the same thing with `x=3, mu=3` ...

tmp-1

I haven't yet figured out where the instability is; a closer comparison with base-R's `nbinom_mu` might provide some hints?

**Comment by kaskr** [comment]
@bbolker I've expressed the formulas through `logit(p)` instead. That seems the right thing to do.
Beyond fixing your examples, it also demonstrates some minor issues with `stats::dnbinom`. When plotting e.g. `c3$dnbinom_robust-c3$dnbinom` one can tell that the R version branches around `size ~ x * 1e10` and this cutoff might not be optimal.

**Comment by bbolker** [comment]
Confirm that this looks good. (Haven't checked `dnbinom`, we can submit a bug report to R later ...)

**Comment by kaskr** [comment]
This is ready to merge.

- Comparing `RTMB::dnbinom_robust` with `Rmpfr::dnbinom` now looks acceptable and, for some inputs, a lot better than `stats::dnbinom`:

```r
    e <- expand.grid(x=c(0, 1, 2, 3, 1e3, 1e6, 1e9),
                     mu=c(1e-100, 1e-50, 1e-10, 1e-1, 1, 2, 3, 1e3, 1e6, 1e9, 1e50, 1e100),
                     var_minus_mu=c(1e-100, 1e-50, 1e-10, 1e-1, 1, 2, 3, 1e3, 1e6, 1e9, 1e50, 1e100))
    e$value <- RTMB:::getValues(RTMB::dnbinom_robust(x = e$x, log_mu = log(e$mu),
                                                     log_var_minus_mu = log(e$var_minus_mu),
                                                     log = TRUE))
    e <- transform(e, size=mu^2/var_minus_mu)
    e$stats <- dnbinom(x = e$x, mu = e$mu, size = e$size, log = TRUE)
    v <- sapply(1:nrow(e),function(i)Rmpfr::dnbinom(x=as.integer(e$x[i]),size=Rmpfr::mpfr(e$size[i],1024),mu=e$mu[i],log=TRUE))
    e$mpfr <- sapply(v, Rmpfr::asNumeric)
    plot(e[,c("value","stats","mpfr")])
```

- The change doesn't seem to break `glmmTMB` tests.

**Pull request merged**
