### PR TITLE
SPA option in MakeADFUN

### PR DESCRIPTION
**Pull request by Blunde1**
Option for TMB to calculate the saddlepoint approximation (SPA) instead of the Laplace approximation.

The idea:
* User supplies the objective function `f` to be the inner problem of the SPA. 
* Specifies `random=s` (saddlepoints) for TMB to calculate the inner problem.

To do this:
* Let `h` calculate the saddlepoint approximation and its gradient. Inherited by `ff` and `MakeADFun`.

Changes:
* Added a `param: SPA=FALSE` to `MakeADFun`.
* If `SPA=TRUE`, then `h` calculates the saddlepoint approximation and its gradient. 
* Examples and tests in *spa_gauss*

### CODE REVIEW

**Comment by kaskr** [comment]
@Blunde1

### SPA
It seems to me the motivation for adding the SPA option is to specify models through the MGF rather than the density (?).
I'm unsure whether SPA is essential enough to justify a new flag to `MakeADFun`, i.e. what models can be specified this way which could not already be handled within the existing framework?

### BesselI
Are you aware of the existing implementations of the Bessel functions? They all allow differentiation wrt. the x and the nu argument - see the [documentation](http://kaskr.github.io/adcomp/group__special__functions.html).

**Comment by Blunde1** [comment]
@kaskr 

### BesselI
This is embarassing. I was not aware that a commit to my fork would automatically be added to the pull-request. In any case, it was not intended for this matter. Thank you for making me aware of the new implementation! I will have to study up on tiny_ad to understand how this works; [I guess this is the document to read](http://www.admb-project.org/developers/workshops/seattle-2016/Kristensen_Anders_Report.pdf)?
I reverted back to the original pull-request.

### SPA
>*"It seems to me the motivation for adding the SPA option is to specify models through the MGF rather than the density (?).*"

Yes. This is sometimes the easiest path, as the MGF is often avilable in closed form, whereas the pdf may have an intractable form.

> "*i.e. what models can be specified this way which could not already be handled within the existing framework?"*

The tiny_ad implementation of the Bessel functions ++ solves some of the problems that could otherwise be approximated with the SPA (e.g. Tweedie, Noncentral chi-squared/mixtures which' pdf involve a Bessel function). However, I believe there are still plenty of interesting applications for the SPA. Here are some examples:

- See the list in the introduction of [this paper](https://arxiv.org/abs/1811.05678) for some general and somewhat standard example situations.
- Direct standard example: [this paper](https://link.springer.com/article/10.1007%2Fs11222-010-9218-8) calculates the MGF of the first terms of Ito-Taylor expansion approximations to the solution of SDEs. The SPA is an automatic and highly accurate way to invert and build the likelihood. The MGF is easily updated if independent jumps  are added to the process (albeit care must be taken with the inversion).
- - [An approximation of small-time probability density functions in a general jump diffusion model](https://www.sciencedirect.com/science/article/abs/pii/S0096300315013351).
- - [Saddlepoint adjusted inversion of characteristic functions](https://arxiv.org/abs/1811.05678) Chapter 3.2 for jump diffusion SPA adjusted inversion.
- A non-standard example: The empirical SPA can be a highly efficient alternative to the bootstrap, and has several applications. One very interesting application is [in this paper](https://projecteuclid.org/euclid.ejs/1527300140) which builds a synthetic likelihood. I've been wanting to implement this in TMB, also employing the new (for me) simulation opportunities(!).

**Comment by kaskr** [comment]
@Blunde1 
I think the idea of specifying intractable densities through the MGF is great and very useful. However, adding it as a flag to `MakeADFun` may be problematic because it might not play well with other arguments to `MakeADFun` (e.g. `profile`) and other TMB functionality (e.g. bias correction, one step residuals etc). In addition you wouldn't be able to use random effects if `SPA=TRUE`.
Before considering your pull request I would like to explore the option of making saddle point approximations available on the C++ side. It is my impression (correct me if I'm wrong) that the convolution property of MGFs tend to generate (block) diagonal Hessians of the inner problem. So, multiple low dimensional SPAs on the C++ side should suffice for most applications?

**Comment by Blunde1** [comment]
@kaskr 
Yes, this should be the case. I have previously done this in a fashion very similar to the [laplace example](https://github.com/kaskr/adcomp/blob/master/tmb_examples/laplace.cpp), using the `autodiff` namespace on the (low dimensional) inner problems as structs. From my experience with this, I had the following problems:
- All Newton iterations on the C++ side that are used for solving the low dimensional inner problems are taped. This is the basis [for this post on the TMB Users forum](https://groups.google.com/forum/#!topic/tmb-users/CV9PRYBF6tk).
- Numerical problems for naive Newton optimization routines. I found error handling difficult due to limitations in if-else. This would be avoided if the initial iterations of the inner-optimization were allowed to run in double (solved if point above is solved).
- Relative to only specifying the inner problem as the objetive function, more code of higher complexity (similar to that of the laplace example above) is needed, at least for now.

**Comment by kaskr** [comment]
Now in master branch

**Pull request closed without merging**
