### PR TITLE
Handle NA for DATA_I*

### PR DESCRIPTION
**Pull request by calbertsen**
There is an issue with NA values for integer data types (#399), which can be handled by, e.g., converting from double to int with Rf_coerceVector.

### CODE REVIEW

**Comment by kaskr** [comment]
@calbertsen and @fishfollower I know you rely on this PR, but it turns out that it's not thread safe, and there's no simple way to fix it (because it invokes the R allocator). Sorry, but will have to roll it back and submit new version to CRAN soon.
See https://github.com/glmmTMB/glmmTMB/issues/1155.

**Comment by bbolker** [comment]
Would it work to write a small wrapper function for coercing integer vectors that records the index values of `NaN`s in the original input, coerces in some thread-safe way, and then sets those indices to INT_MIN?

**Comment by kaskr** [comment]
@bbolker Yes, that would also work, but we are looking for something simpler and faster.

@calbertsen @fishfollower I've made an alternative attempt at handling NA integers (branch 'naint'). The problem is, I can't test if it works as it requires special hardware.

**Comment by bbolker** [comment]
What kind of special hardware? (Why?)

**Comment by kaskr** [comment]
@bbolker Issue #399 says it's for `aarch64-apple-darwin20` which I don't have access to. I'm quite sure my fix (https://github.com/kaskr/adcomp/tree/naint) does the trick, but the more I think about the less I like the idea...
It's too much work for an edge case feature:

- Rarely used, but adds small performance penalty for *every model* passing integers from R!
- Difficult to test and therefore difficult for me to maintain.
- Easy to work around: double NAs work as expected, or choose your own integer NA code.
- Even if the NA integer code is passed consistently from R, it won't propagate consistently in C++ calculations (unlike NA_Real).

**Comment by mebrooks** [comment]
If it helps, I have `aarch64-apple-darwin20.2.0` on my laptop. I plan to be in the office Monday through Wednesday next week.

**Comment by bbolker** [comment]
If there are indeed straightforward workarounds, how about checking input integer data vectors for the presence of `NA_integer` when sanitizing the data, and (if there are any) throwing a warning (or an error) and a pointer to useful documentation?

**Comment by kaskr** [comment]
The problem is that it's OK to pass `NA_integer` from R and then read it from C++ as a double (using `DATA_VECTOR`). And there is no way to know on the R side how the user is going to read the data, so we can't determine if we need to warn about it.

**Comment by bbolker** [comment]
Probably too complicated, but the information doesn't seem too hard to extract from the C++ code. I realize that compilation is a distinct step from tape creation, but one *could* do something like:

* when compiling, scan the code for `DATA_INTEGER` and associated variable names
* attach these names as an attribute (?) to the compiled object (somehow)
* when making the tape, check data for NA values contained in these vectors ...

**Pull request merged**
