### PR TITLE
Fix bug in initial values when using covar options in NUTS

### PR DESCRIPTION
**Pull request by colemonnahan**
Really simple bug pointed out to me by John Wallace. NUTS will not transform the initial values when using a covar matrix. This could lead to very bad initial values and throw off the algorithm entirely, so it's an important one to get right.

There are a few other good bug fixes too, but this is probably the most important one.

### CODE REVIEW

**Comment by kaskr** [comment]
This pull request is not clean. Everything, except 8e86b61, is already (squashed) in the master branch.

**Comment by colemonnahan** [comment]
Kasper: Sorr y I didn't see that. How do merge in your repo into my forked
repo? I get lots of conflicts when I try.. like it doesn't recognize the
"squashed" commit (I'm new to that).

Any easy way to do that?

**Comment by kaskr** [comment]
Create a fresh branch, pull the official master branch (assert that SHA is correct). Then
git cherry-pick 8e86b61

**Comment by colemonnahan** [comment]
I was working in master so any new branch has the same issue. I've dug around online and can't seem to find this issue. Maybe it's easier to just delete the repo and re-fork yours? Any downside to that?

It's literally deleting a line of code and I've spend an hour reading online already.

**Comment by kaskr** [comment]
No problem, I have cherry-picked your change here: 2b9513e3f6
In the future it's probably easiest if you re-fork before making changes.

**Comment by colemonnahan** [comment]
Is that just because you squashed the commits? So I should delete my fork and reclone (re-fork??) every time you squash my commits? Or maybe it'd be easiest for me to squash them before the pull request?

I've never had this problem before, and admittedly don't enjoy learning the esoteric git commands.

**Comment by kaskr** [comment]
I would do it this way:

* Let your own master branch be an exact copy of the official master
  branch. Synchronize frequently.
* Never commit directly to your master. Work on a local branch and
  send pull requests only for the local branch.
* Once your pull request is accepted, delete you local branch and
  synchronize the master branch.

**Comment by colemonnahan** [comment]
Yes this makes a lot of sense. I was doing that originally with a local `mcmc` branch but when you merged your `mcmc` branch into master I stopped. 

I'd suggest writing that up in the wiki for others who are going to contribute code. Most users will be like me and just want to be told a workflow that will avoid conflicts. Should smooth out the process.

**Comment by kaskr** [comment]
Good suggestion - have given it a try here:
https://github.com/kaskr/adcomp/wiki/Development

**Pull request closed without merging**
