### PR TITLE
Compois sample

### PR DESCRIPTION
**Pull request by kaskr**
Simulate from Conway-Maxwell-Poisson

### CODE REVIEW

**Comment by mebrooks** [comment]
This is a great addition to TMB. I was working on compois simulation method in `glmmTMB`. This is what I came up with (adapted from the function `makeCMPdata` from R package `COMPoissonReg`). It uses the cumulative density, but I didn't use `dcompois2` to calculate it because that would require calculating Z in each iteration of the while loop.
```
        SIMULATE{//there could be a faster way, but maybe not
          s1 = mu(i); //mean
          s2 = 1/phi(i); //nu
          yobs(i) = Type(0); //minimum possible
          Type cmptest = runif(Type(0),Type(1));
          Type lambda = exp(compois_calc_loglambda(log(s1), s2));
          Type zinv = 1/exp(compois_calc_logZ(log(lambda), s2));
          Type py = zinv; //prob of y=0
          while(py < cmptest){
            yobs(i) += Type(1); //y++ wouldn't compile
            py += pow(lambda, yobs(i))/pow(exp(lgamma(yobs(i)+Type(1))), s2)*zinv; 
          }
        }
```
I briefly looked at `atomic::compois_utils::simulate` and I see it's more complex. Do you think it will be more robust and accurate than this algorithm from `COMPoissonReg`?

**Comment by mebrooks** [comment]
I forgot to mention, for a large simulation with the seed set, the code above took 1.6 seconds and `rcompois2` took 1.5 seconds.

**Comment by kaskr** [comment]
The problem with the quantile transformed uniform is that you'll have to sum up millions of terms in some of the edge cases. For instance, say you get `cmptest` close to one and we are in the over dispersed case e.g. `nu=1e-3` and `lambda=1.02`...
In comparison, the rejection sampler on average uses 1-2 proposals *and* it does not require the normalizing constant, hence in principle it is exact. It is slightly more complex, yes, but it seems to handle the entire parameter space equally well.

The disappointing speed of `rcompois2` is caused by the fact that it requires `calc_loglambda`. Hopefully, the speed of `calc_loglambda` can be improved eventually.

**Comment by mebrooks** [comment]
Sounds good to me. I'll use `rcompois2` in `glmmTMB`. Thanks!

**Pull request merged**
