### PR TITLE
make .find.epsilon more stable when in tails of posterior

### PR DESCRIPTION
**Pull request by colemonnahan**
The algorithm to find a reasonable starting eps for the dual averaging tuning algorithm had some issues. Basically it takes a big jump from your initial position and looks at the probability of accepting that state, and keeps reducing the step size until that's about 1/2. The problem is if that first jump is into the tails, numerical issues can arise. I've fixed it so that if there's a non-finite calculate to proceed with halving the jump size. Thus instead of throwing an error it just keeps reducing the jump size by half until it is finite and then meets the roughly 1/2 condition. It should now be much more stable for generic problem with arbitrary initial values.

### CODE REVIEW

**Comment by colemonnahan** [comment]
I added some non-finite checks and tweaked the DA algorithm. That seems to have fixed those issues and it appears to be much more stable. The 2d example runs w/o any issues now.

I also added some quick code to the example: (1) switch to using adaptive for HMC and NUTS; (2) track of the final adapted epsilon and plot them/check for issues; (3) tweaked the plots a bit so they're easier to see.

**Comment by jmannseth** [comment]
Hi,

I am working with your NUTS  (and HMC) code. 
My model in C++ is a bivariate normal distribution. 

The issue arises when trying to use NUTS or HMC on the obj function, as the samples I get are not correct. 

I have samples from using the same model with NUTS in MATLAB (for comparison) and a Kolmogorov-Smirnov test  (of the samples from R and from MATLAB) rejects H0.

I have added a file that shows a plot of the MATLAB samples:
[matlab_samples.pdf](https://github.com/kaskr/adcomp/files/34084/matlab_samples.pdf)


Below I have added the code of the two files to illustrate the issue.

Thank you very much!

##################################
The c++ file: normal.cpp

#include <TMB.hpp>

template<class Type>
Type objective_function<Type>::operator()()
{
  DATA_MATRIX(sigma);
  DATA_VECTOR(mu);
  PARAMETER_VECTOR(x);

  Type norm=0;
  using namespace density;
  MVNORM_t<Type> min_mvnorm(sigma);   // Definerer en 0-mean mvnorm objekt

  // Definition: Q = inverse(sigma)
  // min_mvnorm.Quadform(x)    = x*Q*x
  //min_mvnorm.logdetQ	   =  log(det(Q))

   norm = -log(2) -log(3.14159) + 0.5 * min_mvnorm.logdetQ - 0.5 * min_mvnorm.Quadform(x-mu);
  
  return norm;
}

#################################

#################################

The R file: normal.R

library(TMB)

set.seed(123)

compile("normal.cpp")
dyn.load(dynlib("normal"))

#Data: Covariance matrix sigma and mean (zero) vector mu
sigma = matrix(c(1, 0.95, 0.95, 1), nrow = 2, ncol = 2)
mu = rep(0,nrow(sigma))
#Parameters: vector x
x = rep(0,nrow(sigma))

#Bivariate normal distribution
obj_normal <- MakeADFun(data = list(sigma=sigma, mu=mu),
                   parameters=list(x=x), DLL="normal")

#The output from obj_normal gives the correct function value and covariance matrix:
obj_normal$fn()
-(solve(obj_normal$he()))

#The issue starts with the sampling
hmc_normal = mcmc(obj = obj_normal, nsim = 1000, algorithm = 'HMC', eps=.5,  params.init = obj_normal$par, L=5)
#For HMC: Get acceptance rate = 0, all samples = 0

nuts_normal = mcmc(obj = obj_normal, nsim = 1000, algorithm = 'NUTS', eps= 0.5, params.init = obj_normal$par)
#For NUTS: Generates samples, or gives warning:
#Warning messages:
  #1: In runif(n = 1, min = 0, max = exp(.calculate.H(theta = theta,  ... : NAs produced
  #2: ...


plot(hmc_normal)
plot(nuts_normal)
#################################

**Comment by colemonnahan** [comment]
@jmannseth The algorithms were tested extensively with a multivariate normal so it definitely should work. I wonder if something is wrong with your implementation of the C++ code. @kaskr is the expert, but when I made my simple model I used:

````
#include <TMB.hpp>
template<class Type>
Type objective_function<Type>::operator() ()
{
  DATA_MATRIX(covar);
  PARAMETER_VECTOR(X); // parameters
  using namespace density;
  MVNORM_t<Type> neg_log_density(covar);
  Type nll= neg_log_density(X);
  REPORT(nll);
  return(nll);
}
````
and that worked fine. Maybe try adapting yours to match this approach??

**Comment by jmannseth** [comment]
Thank you for the quick reply!

**Comment by colemonnahan** [comment]
@jmannseth I forgot to mention before that if you're still having issues and getting 0 acceptance with your model, you should try lowering the `eps` value, or setting it to NULL. If it's too big the jumps will take you into low density areas and be rejected, so you never move. The adaptive nature of the algorithms will slowly lower it until you get the target acceptance rate.

Hope that helps and let us know if you get it working.

**Comment by colemonnahan** [comment]
This latest bug fix should also greatly increase stability, particularly for models where `eps=1` is really big. The problem was the adaptation algorithm initiated at 1 for all models, not the reasonable value found dynamically with `.find.epsilon`.

**Comment by kaskr** [comment]
Merged

**Pull request closed without merging**
