### PR TITLE
Rtweedie

### PR DESCRIPTION
**Pull request by kaskr**

### CODE REVIEW

**Comment by kaskr** [comment]
Copy `rtweedie` from `glmmTMB`

**Comment by mebrooks** [comment]
I wonder if this will cause a conflict with glmmTMB. Eventually the redundant `rtweedie` definition should be removed.

**Comment by kaskr** [comment]
Shouldn't cause conflicts because glmmTMB has its version declared in a namespace.

**Comment by bbolker** [comment]
I'm not sure that's true, but I think we can deal with it if it does cause a conflict: we can conditionally import based on TMB package version, see [here](https://github.com/lme4/lme4/blob/master/NAMESPACE#L31-L35)

**Comment by kaskr** [comment]
@mebrooks @bbolker  Forgot to mention that the travis setup checks that glmmTMB.cpp still builds when TMB is updated. As an additional check I just installed glmmTMB with the new TMB version. It worked without problems.

**Comment by bbolker** [comment]
Wasn't paying enough attention: thought that `rtweedie` was being defined at the R level, not the C++ level. Still would be good to switch `glmmTMB` over to using the `TMB` version later, once this version of `TMB` is on CRAN ...

**Pull request merged**
