### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by John-R-Wallace**
Adding a function to do 3D plots of mcmc() output.

### CODE REVIEW

**Comment by colemonnahan** [comment]
@John-R-Wallace Thanks for your additions. I have a few thoughts:

(1) I have been thinking I should add the objective function to the returned parameter data frame in all of the algorithms. For big models it's a huge waste to calculate them after the fact since `fn` is calculated internally anyway and I would just have to save it.

(2) I've done some similar work with creating some of my own plotting functions that play nicely with MCMC output. I think it's really useful but I'm not sure it belongs in TMB since it's generic code that could be applied to output from any software (e.g., ADMB). The way Stan and LaplacesDemon do it is use S4 and S3 classes (respectively) and define generic functions that work out the returned object class (e.g,. stan-fit). I like this approach a lot but hadn't gotten around to trying to implement it. Perhaps this type of plotting code would be better placed in a package like [mcmcplots](https://cran.r-project.org/web/packages/mcmcplots/mcmcplots.pdf) or something similar (I have to admit I haven't looked into these packages yet).

(3) I find it difficult to interpret the 3D plots and prefer pairwise scatterplots. I tend to add the MLE estimates and covariances on top of the samples to see what's happening, then put either the trace, ACF, or histogram on the diagonal. I've attached a rough version of this below from an SS3 model. Would be happy to collaborate on some code specific to TMB/ADMB. One huge advantage is we'll have robust MLE estimates which none of the other packages I've seen take advantage of.

@kaskr What are your thoughts on what should be included in the TMB source?

pairs_min_ess

**Comment by bbolker** [comment]
My two cents:  there are *quite a few* plotting back-ends for MCMC already implemented in R: before you invent yet another set of method, take a look around and (1) see what you can borrow and (2) see what nice features you can take from existing packages ... this is also difficult because, as you've already seen, people have a wide variety of graphical tastes!

- `coda::xyplot` (trace plots) and `coda::densityplot` (I much prefer each of these lattice-based examples to the combined, uglier base-graphics `plot.mcmc` method; 
- `lattice::splom` handles pairs plots pretty nicely once the results are converted to something matrix-like;
- `r2jags` has its own plotting method, most useful for cases where the output contains vectors;
-  `plotMCMC` has nice lattice-based defaults, but doesn't handle multiple chains
- `mcmcplots` does the HTML front-end thing
- corrplots is nice if you just want to plot correlations
- `rstan` has some nice plotting methods for pairs plots that do smoothed scatterplots
- hexbin plots are another useful alternative for pairs plots ...

**Comment by kaskr** [comment]
@John-R-Wallace Thanks for the pull request.
In general only the following categories of patches will be considered:

1. Those that substantially improve the AD computational methods.
2. Code cleanups and reductions.
3. Documentation patches.

Potentially there are many useful features to put on top of the
current MCMC functionality (e.g. thinning, convergence diagnostics,
plotting etc). However, it would have to implemented as part of other
packages.

**Comment by John-R-Wallace** [comment]
@colemonnahan 
Without the objective function values in $par it seemed reasonable to wait until after thinning ($parThin) since then usually only 500 - 1000 rows are kept. (I did think to ask for them in $par.)

Collaboration on MCMC plots would be good.


@bbolker 
Thanks for review of MCMC plots.


@kaskr 
Thanks for consideration.

**Pull request closed without merging**
